apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      color: blue
  template:
    metadata:
      labels:
        app: backend
        color: blue
    spec:
      containers:
        - name: backend
          image: 629585638563.dkr.ecr.us-east-1.amazonaws.com/devops-final/backend:latest
          ports:
            - containerPort: 8800
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database

      imagePullSecrets:
        - name: regcred