apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: qa
spec:
  selector:
    app: backend
    color: blue  # Route by default to blue — will be switched by the workflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8800
  type: LoadBalancer