apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2-blue
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-2
      color: blue
  template:
    metadata:
      labels:
        app: api-2
        color: blue
    spec:
      containers:
        - name: api-2
          image: 629585638563.dkr.ecr.us-east-1.amazonaws.com/devops-final/api-2:latest
          ports:
            - containerPort: 8804