apiVersion: v1
kind: Service
metadata:
  name: api-2
  namespace: qa
spec:
  selector:
    app: api-2
    color: blue  # Route by default to blue — will be switched by the workflow
  ports:
    - port: 8804
      targetPort: 8804
  type: ClusterIP