apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      color: green
  template:
    metadata:
      labels:
        app: frontend
        color: green
    spec:
      containers:
        - name: frontend
          image: 629585638563.dkr.ecr.us-east-1.amazonaws.com/devops-final/frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: VITE_BACKEND_HOST
              value: backend
            - name: VITE_BACKEND_PORT
              value: "8800"
            - name: VITE_API1_HOST
              value: api-1
            - name: VITE_API1_PORT
              value: "8802"
            - name: VITE_API2_HOST
              value: api-2
            - name: VITE_API2_PORT
              value: "8804"
            - name: VITE_PROTO
              value: http
            - name: VITE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace