apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: qa
spec:
  selector:
    app: frontend
    color: blue  # Route by default to blue — will be switched by the workflow
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP