apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      color: blue
  template:
    metadata:
      labels:
        app: frontend
        color: blue
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/g1l2p8r3/devops-final/api-1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred