apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1-green
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-1
      color: green
  template:
    metadata:
      labels:
        app: api-1
        color: green
    spec:
      containers:
        - name: api-1
          image: 629585638563.dkr.ecr.us-east-1.amazonaws.com/devops-final/api-1:latest
          ports:
            - containerPort: 8802
      imagePullSecrets:
        - name: regcred