apiVersion: v1
kind: Service
metadata:
  name: api-1
  namespace: qa
spec:
  selector:
    app: api-1
    color: blue  # Route by default to blue — will be switched by the workflow
  ports:
    - port: 8802
      targetPort: 8802
  type: ClusterIP