name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      auto_promote:
        description: 'Automatically promote all successful UAT deployments'
        type: boolean
        default: false
      frontend:
        description: 'Promote frontend?'
        type: boolean
        default: false
      backend:
        description: 'Promote backend?'
        type: boolean
        default: false
      api-1:
        description: 'Promote api-1?'
        type: boolean
        default: false
      api-2:
        description: 'Promote api-2?'
        type: boolean
        default: false

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.auto_promote == 'true' }}
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}

    steps:
      - name: Find latest UAT workflow run
        id: find-workflow
        uses: actions/github-script@v6
        with:
          script: |
            const workflow_name = "Promote to UAT";
            // First try to get the workflow by name
            let workflowsResponse = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            let workflowId = null;
            for (const workflow of workflowsResponse.data.workflows) {
              if (workflow.name === workflow_name) {
                workflowId = workflow.id;
                break;
              }
            }

            // If we couldn't find the workflow by name, try the filename as fallback
            if (!workflowId) {
              console.log(`Could not find workflow with name "${workflow_name}", trying filename`);
              workflowId = 'promote-to-uat.yaml';
            }

            const workflows = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              status: 'success',
              per_page: 1
            });

            if (workflows.data.workflow_runs.length === 0) {
              console.log('No successful UAT workflow runs found');
              return;
            }

            const workflowRun = workflows.data.workflow_runs[0];
            console.log(`Found workflow run: ${workflowRun.id}`);
            return workflowRun.id;

      - name: Download artifact
        if: steps.find-workflow.outputs.result
        uses: actions/github-script@v6
        with:
          script: |
            const workflowRunId = ${{ steps.find-workflow.outputs.result }};

            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: workflowRunId
            });

            const matchArtifact = artifacts.data.artifacts.find(artifact => {
              return artifact.name === "deployed-services-uat"
            });

            if (!matchArtifact) {
              console.log('No artifacts found');
              return;
            }

            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip'
            });

            const fs = require('fs');
            fs.writeFileSync('${{ github.workspace }}/deployed-services.zip', Buffer.from(download.data));

      - name: Extract artifact
        if: steps.find-workflow.outputs.result
        run: |
          if [ -f "deployed-services.zip" ]; then
            unzip -o deployed-services.zip
          else
            echo "No artifact file found to extract"
          fi

      - name: Set matrix
        id: set-matrix
        run: |
          if [ -f "deployed_services.json" ]; then
            echo "services<<EOF" >> $GITHUB_OUTPUT
            cat deployed_services.json >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "services={\"services\":[]}" >> $GITHUB_OUTPUT
          fi

  prepare-manual-matrix:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.auto_promote != 'true' }}
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}

    steps:
      - name: Set matrix for manual selection
        id: set-matrix
        run: |
          # Create a JSON array of services to promote
          echo "{" > services.json
          echo "  \"services\": [" >> services.json

          # Add services based on inputs
          if [ "${{ github.event.inputs.frontend }}" = "true" ]; then
            echo "    {\"name\": \"frontend\"}," >> services.json
          fi

          if [ "${{ github.event.inputs.backend }}" = "true" ]; then
            echo "    {\"name\": \"backend\"}," >> services.json
          fi

          if [ "${{ github.event.inputs.api-1 }}" = "true" ]; then
            echo "    {\"name\": \"api-1\"}," >> services.json
          fi

          if [ "${{ github.event.inputs.api-2 }}" = "true" ]; then
            echo "    {\"name\": \"api-2\"}," >> services.json
          fi

          # Remove trailing comma if any services were added
          sed -i '$ s/,$//' services.json

          echo "  ]" >> services.json
          echo "}" >> services.json

          echo "services<<EOF" >> $GITHUB_OUTPUT
          cat services.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  determine-matrix:
    runs-on: ubuntu-latest
    needs: [ download-artifact, prepare-manual-matrix ]
    if: |
      always() && (
        (needs.download-artifact.result == 'success' && github.event.inputs.auto_promote == 'true') ||
        (needs.prepare-manual-matrix.result == 'success' && github.event.inputs.auto_promote != 'true')
      )
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      debug_info: ${{ steps.debug.outputs.info }}

    steps:
      - name: Debug job inputs
        id: debug
        run: |
          echo "::notice::auto_promote: ${{ github.event.inputs.auto_promote }}"
          echo "::notice::download-artifact.result: ${{ needs.download-artifact.result }}"
          echo "::notice::prepare-manual-matrix.result: ${{ needs.prepare-manual-matrix.result }}"

          # Create debug info for output
          echo "info<<EOF" >> $GITHUB_OUTPUT
          echo "auto_promote: ${{ github.event.inputs.auto_promote }}" >> $GITHUB_OUTPUT
          echo "download-artifact.result: ${{ needs.download-artifact.result }}" >> $GITHUB_OUTPUT
          echo "prepare-manual-matrix.result: ${{ needs.prepare-manual-matrix.result }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Set matrix
        id: set-matrix
        run: |
          # Print the raw services output for debugging
          if [ "${{ github.event.inputs.auto_promote }}" = "true" ]; then
            echo "::notice::Raw services from download-artifact: ${{ needs.download-artifact.outputs.services }}"
          else
            echo "::notice::Raw services from prepare-manual-matrix: ${{ needs.prepare-manual-matrix.outputs.services }}"
          fi

          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          if [ "${{ github.event.inputs.auto_promote }}" = "true" ]; then
            echo '${{ needs.download-artifact.outputs.services }}' >> $GITHUB_OUTPUT
          else
            echo '${{ needs.prepare-manual-matrix.outputs.services }}' >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

          # Create a temporary file to see what's being set
          if [ "${{ github.event.inputs.auto_promote }}" = "true" ]; then
            echo '${{ needs.download-artifact.outputs.services }}' > matrix_content.json
          else
            echo '${{ needs.prepare-manual-matrix.outputs.services }}' > matrix_content.json
          fi

          echo "::notice::Matrix content from file:"
          cat matrix_content.json

  check-matrix:
    needs: determine-matrix
    runs-on: ubuntu-latest
    if: always()
    outputs:
      has_services: ${{ steps.check.outputs.has_services }}
      matrix_json: ${{ steps.check.outputs.matrix_json }}
      determine_matrix_result: ${{ needs.determine-matrix.result }}

    steps:
      - name: Debug determine-matrix result
        run: |
          echo "::notice::determine-matrix result: ${{ needs.determine-matrix.result }}"
          echo "::notice::determine-matrix debug info: ${{ needs.determine-matrix.outputs.debug_info }}"
      - name: Check matrix structure
        id: check
        run: |
          # Print the raw matrix output for debugging
          echo "::notice::Raw matrix from determine-matrix: ${{ needs.determine-matrix.outputs.matrix }}"

          # Check if matrix output is empty or null
          if [ -z "${{ needs.determine-matrix.outputs.matrix }}" ]; then
            echo "::notice::Matrix output is empty or null"
            echo "has_services=false" >> $GITHUB_OUTPUT
            echo "matrix_json={\"services\":[]}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Parse the matrix output to check its structure
          MATRIX='${{ needs.determine-matrix.outputs.matrix }}'
          echo "$MATRIX" > matrix.json

          # Check if the matrix has a services property
          if grep -q '"services"' matrix.json; then
            echo "::notice::Matrix has services property"

            # Check if the services array is empty
            if grep -q '"services": *\[\]' matrix.json; then
              echo "::notice::Services array is empty"
              echo "has_services=false" >> $GITHUB_OUTPUT
            else
              echo "::notice::Services array has items"
              echo "has_services=true" >> $GITHUB_OUTPUT
            fi

            echo "matrix_json=$(jq -c . matrix.json)" >> $GITHUB_OUTPUT
          else
            echo "::notice::Matrix does not have services property"
            echo "has_services=false" >> $GITHUB_OUTPUT
            echo "matrix_json={\"services\":[]}" >> $GITHUB_OUTPUT
          fi

          # Print the matrix content for debugging
          echo "::notice::Matrix content:"
          cat matrix.json

          # Additional debugging to verify the output values
          echo "::notice::has_services output value: $(grep has_services $GITHUB_OUTPUT | cut -d= -f2)"
          echo "::notice::matrix_json output format check:"
          grep -A 10 matrix_json $GITHUB_OUTPUT

  promote-to-prod:
    needs: check-matrix
    runs-on: ubuntu-latest
    if: always()

    strategy:
      matrix:
        service: ${{ fromJson(needs.check-matrix.outputs.matrix_json).services }}
      fail-fast: false

    env:
      ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      REPO_PREFIX: devops-final

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Get current image from UAT
        id: get-image
        run: |
          SERVICE=${{ matrix.service.name }}

          # For auto-promote, use the image tag from the artifact
          # For manual selection, get the current image from UAT
          if [ "${{ github.event.inputs.auto_promote }}" = "true" ]; then
            IMAGE_TAG=${{ matrix.service.image_tag }}
            echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          else
            # Get the current color in UAT
            CURRENT_COLOR=$(kubectl get svc $SERVICE -n uat -o jsonpath='{.spec.selector.color}')

            # Get the image from the current deployment in UAT
            IMAGE=$(kubectl get deployment/$SERVICE-$CURRENT_COLOR -n uat -o jsonpath='{.spec.template.spec.containers[0].image}')
            IMAGE_TAG=$(echo $IMAGE | cut -d ':' -f2)

            echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Blue/green deploy to Production
        run: |
          SERVICE=${{ matrix.service.name }}
          IMAGE_TAG=${{ steps.get-image.outputs.image_tag }}

          echo "Promoting $SERVICE:$IMAGE_TAG from UAT to Production"

          # Get current color in Production
          CURRENT_COLOR=$(kubectl get svc $SERVICE -n prod -o jsonpath='{.spec.selector.color}')
          if [ "$CURRENT_COLOR" = "green" ]; then NEW_COLOR=blue; else NEW_COLOR=green; fi

          echo "Current color is $CURRENT_COLOR, deploying to $NEW_COLOR"

          # Update image for the new color
          kubectl set image deployment/$SERVICE-$NEW_COLOR \
            $SERVICE=$ECR_URI/$REPO_PREFIX/$SERVICE:$IMAGE_TAG -n prod

          # Wait for rollout to complete
          kubectl rollout status deployment/$SERVICE-$NEW_COLOR -n prod

          # If deployment was successful, switch traffic to the new color
          if [ $? -eq 0 ]; then
            echo "Deployment successful, switching traffic to $NEW_COLOR"
            kubectl patch service $SERVICE -n prod -p \
              "{\"spec\": {\"selector\": {\"app\": \"$SERVICE\", \"color\": \"$NEW_COLOR\"}}}"

            # If this is the frontend service, get and display the URL
            if [ "$SERVICE" = "frontend" ]; then
              # Wait a moment for the LoadBalancer to update
              sleep 10
              FRONTEND_URL=$(kubectl get svc $SERVICE -n prod -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
              if [ -z "$FRONTEND_URL" ]; then
                FRONTEND_URL=$(kubectl get svc $SERVICE -n prod -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
              fi
              if [ -n "$FRONTEND_URL" ]; then
                echo "::notice::Frontend URL (Production): http://$FRONTEND_URL"
              else
                echo "::warning::Could not determine frontend URL for Production environment"
              fi
            fi

            echo "Successfully promoted $SERVICE to Production"
          else
            echo "Deployment failed, keeping traffic on $CURRENT_COLOR"
            # Don't switch traffic if deployment failed
            exit 1
          fi
